<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnimalSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('animals')->insert([
            [
                'nome' => 'Rex',
                'raca' => 'Labrador',
                'data_ficha' => '2026-01-10',
                'especie' => 'Cachorro',
                'sexo' => 'Macho',
                'idade' => 4,
                'peso' => 28.50,
                'cor' => 'Caramelo',
                'data_entrada' => '2026-01-10',
                'observacoes' => 'Animal dócil.',
                'animal_state_id' => 1,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Mimi',
                'raca' => 'Persa',
                'data_ficha' => '2026-01-15',
                'especie' => 'Gato',
                'sexo' => 'Fêmea',
                'idade' => 2,
                'peso' => 4.20,
                'cor' => 'Branco',
                'data_entrada' => '2026-01-15',
                'observacoes' => 'Muito tranquila.',
                'animal_state_id' => 2,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Thor',
                'raca' => 'Pastor Alemão',
                'data_ficha' => '2026-02-01',
                'especie' => 'Cachorro',
                'sexo' => 'Macho',
                'idade' => 5,
                'peso' => 35.00,
                'cor' => 'Preto e Marrom',
                'data_entrada' => '2026-02-01',
                'observacoes' => 'Necessita espaço amplo.',
                'animal_state_id' => 3,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Luna',
                'raca' => 'SRD',
                'data_ficha' => '2026-02-12',
                'especie' => 'Gato',
                'sexo' => 'Fêmea',
                'idade' => 1,
                'peso' => 3.10,
                'cor' => 'Cinza',
                'data_entrada' => '2026-02-12',
                'observacoes' => 'Filhote resgatada.',
                'animal_state_id' => 4,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Bob',
                'raca' => 'Vira-lata',
                'data_ficha' => '2026-03-05',
                'especie' => 'Cachorro',
                'sexo' => 'Macho',
                'idade' => 7,
                'peso' => 18.70,
                'cor' => 'Preto',
                'data_entrada' => '2026-03-05',
                'observacoes' => 'Castrado.',
                'animal_state_id' => 5,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Mel',
                'raca' => 'Golden Retriever',
                'data_ficha' => '2026-03-12',
                'especie' => 'Cachorro',
                'sexo' => 'Fêmea',
                'idade' => 3,
                'peso' => 24.80,
                'cor' => 'Dourado',
                'data_entrada' => '2026-03-12',
                'observacoes' => 'Muito sociável.',
                'animal_state_id' => 4,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Nina',
                'raca' => 'Siamês',
                'data_ficha' => '2026-03-15',
                'especie' => 'Gato',
                'sexo' => 'Fêmea',
                'idade' => 2,
                'peso' => 3.80,
                'cor' => 'Bege',
                'data_entrada' => '2026-03-15',
                'observacoes' => 'Gosta de colo.',
                'animal_state_id' => 1,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Max',
                'raca' => 'Pinscher',
                'data_ficha' => '2026-03-18',
                'especie' => 'Cachorro',
                'sexo' => 'Macho',
                'idade' => 6,
                'peso' => 5.20,
                'cor' => 'Preto',
                'data_entrada' => '2026-03-18',
                'observacoes' => 'Bastante ativo.',
                'animal_state_id' => 2,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Amora',
                'raca' => 'SRD',
                'data_ficha' => '2026-03-20',
                'especie' => 'Gato',
                'sexo' => 'Fêmea',
                'idade' => 1,
                'peso' => 2.90,
                'cor' => 'Preto',
                'data_entrada' => '2026-03-20',
                'observacoes' => 'Resgatada recentemente.',
                'animal_state_id' => 1,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Toby',
                'raca' => 'Beagle',
                'data_ficha' => '2026-03-25',
                'especie' => 'Cachorro',
                'sexo' => 'Macho',
                'idade' => 4,
                'peso' => 13.40,
                'cor' => 'Tricolor',
                'data_entrada' => '2026-03-25',
                'observacoes' => 'Adora brincar.',
                'animal_state_id' => 5,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Lili',
                'raca' => 'Persa',
                'data_ficha' => '2026-04-01',
                'especie' => 'Gato',
                'sexo' => 'Fêmea',
                'idade' => 5,
                'peso' => 4.50,
                'cor' => 'Branco',
                'data_entrada' => '2026-04-01',
                'observacoes' => 'Calma e carinhosa.',
                'animal_state_id' => 3,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Zeus',
                'raca' => 'Rottweiler',
                'data_ficha' => '2026-04-04',
                'especie' => 'Cachorro',
                'sexo' => 'Macho',
                'idade' => 8,
                'peso' => 42.30,
                'cor' => 'Preto e Marrom',
                'data_entrada' => '2026-04-04',
                'observacoes' => 'Muito obediente.',
                'animal_state_id' => 4,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Pipoca',
                'raca' => 'SRD',
                'data_ficha' => '2026-04-10',
                'especie' => 'Cachorro',
                'sexo' => 'Fêmea',
                'idade' => 2,
                'peso' => 9.60,
                'cor' => 'Branco',
                'data_entrada' => '2026-04-10',
                'observacoes' => 'Muito brincalhona.',
                'animal_state_id' => 2,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Fred',
                'raca' => 'SRD',
                'data_ficha' => '2026-04-15',
                'especie' => 'Gato',
                'sexo' => 'Macho',
                'idade' => 3,
                'peso' => 4.10,
                'cor' => 'Laranja',
                'data_entrada' => '2026-04-15',
                'observacoes' => 'Muito curioso.',
                'animal_state_id' => 1,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Belinha',
                'raca' => 'Shih Tzu',
                'data_ficha' => '2026-04-20',
                'especie' => 'Cachorro',
                'sexo' => 'Fêmea',
                'idade' => 6,
                'peso' => 7.80,
                'cor' => 'Branco e Marrom',
                'data_entrada' => '2026-04-20',
                'observacoes' => 'Vacinada e castrada.',
                'animal_state_id' => 5,
                'animal_state_changed_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
