<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LembreteSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('lembretes')->insert([
            [
                'nome' => 'Vacinação Antirrábica',
                'descricao' => 'Aplicar vacina antirrábica nos animais cadastrados.',
                'data' => '2026-06-15',
                'visualizado' => false,
                'tipo_recorrencia' => 'anual',
                'intervalo_dias' => null,
                'dia_semana' => null,
                'dia_mes' => 15,
                'data_fim' => null,
                'hora' => '09:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Vermifugação Geral',
                'descricao' => 'Realizar vermifugação dos animais do abrigo.',
                'data' => '2026-06-18',
                'visualizado' => false,
                'tipo_recorrencia' => 'mensal',
                'intervalo_dias' => null,
                'dia_semana' => null,
                'dia_mes' => 18,
                'data_fim' => null,
                'hora' => '08:30:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Consulta Veterinária',
                'descricao' => 'Avaliação clínica dos animais recém-resgatados.',
                'data' => '2026-06-12',
                'visualizado' => false,
                'tipo_recorrencia' => 'nenhuma',
                'intervalo_dias' => null,
                'dia_semana' => null,
                'dia_mes' => null,
                'data_fim' => null,
                'hora' => '14:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Feira de Adoção',
                'descricao' => 'Evento mensal para adoção responsável.',
                'data' => '2026-06-20',
                'visualizado' => false,
                'tipo_recorrencia' => 'mensal',
                'intervalo_dias' => null,
                'dia_semana' => 6,
                'dia_mes' => null,
                'data_fim' => '2027-06-20',
                'hora' => '10:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Limpeza dos Canis',
                'descricao' => 'Rotina de higienização completa dos espaços.',
                'data' => '2026-06-11',
                'visualizado' => true,
                'tipo_recorrencia' => 'diaria',
                'intervalo_dias' => 1,
                'dia_semana' => null,
                'dia_mes' => null,
                'data_fim' => null,
                'hora' => '07:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Prestação de Contas',
                'descricao' => 'Atualizar relatório financeiro do abrigo.',
                'data' => '2026-06-30',
                'visualizado' => false,
                'tipo_recorrencia' => 'mensal',
                'intervalo_dias' => null,
                'dia_semana' => null,
                'dia_mes' => 30,
                'data_fim' => null,
                'hora' => '17:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Castração Agendada',
                'descricao' => 'Procedimento de castração para animais aptos.',
                'data' => '2026-06-16',
                'visualizado' => false,
                'tipo_recorrencia' => 'nenhuma',
                'intervalo_dias' => null,
                'dia_semana' => null,
                'dia_mes' => null,
                'data_fim' => null,
                'hora' => '13:30:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Reunião com Voluntários',
                'descricao' => 'Alinhamento de atividades da semana.',
                'data' => '2026-06-13',
                'visualizado' => false,
                'tipo_recorrencia' => 'semanal',
                'intervalo_dias' => null,
                'dia_semana' => 6,
                'dia_mes' => null,
                'data_fim' => null,
                'hora' => '18:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Compra de Ração',
                'descricao' => 'Verificar estoque e realizar reposição.',
                'data' => '2026-06-14',
                'visualizado' => false,
                'tipo_recorrencia' => 'quinzenal',
                'intervalo_dias' => 15,
                'dia_semana' => null,
                'dia_mes' => null,
                'data_fim' => null,
                'hora' => '11:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Atualizar Redes Sociais',
                'descricao' => 'Publicar animais disponíveis para adoção.',
                'data' => '2026-06-12',
                'visualizado' => false,
                'tipo_recorrencia' => 'semanal',
                'intervalo_dias' => null,
                'dia_semana' => 5,
                'dia_mes' => null,
                'data_fim' => null,
                'hora' => '19:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Reunião',
                'descricao' => 'Reunião com donos de ONGs para discutir cooperatividade.',
                'data' => '2026-06-11',
                'visualizado' => false,
                'tipo_recorrencia' => 'nenhuma',
                'intervalo_dias' => null,
                'dia_semana' => null,
                'dia_mes' => null,
                'data_fim' => null,
                'hora' => '19:00:00',
                'ativo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}